<?php
include 'connection.php';
require_once('tcpdf/tcpdf.php'); // Ensure the path is correct to the TCPDF library
session_start();

// Ensure only admins can access
if ($_SESSION['role'] != 'admin') {
    header('Location: login.php');
    exit;
}

// Set content type as JSON for AJAX response
header('Content-Type: application/json');

try {
    // Fetch total number of inmates
    $result = $conn->query("SELECT COUNT(*) as total FROM inmate");
    if ($result && $row = $result->fetch_assoc()) {
        $totalInmates = $row['total'];
    } else {
        throw new Exception("Could not retrieve total inmate count.");
    }

    // Initialize TCPDF
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Admin');
    $pdf->SetTitle('Inmate Report');
    $pdf->SetHeaderData('', '', 'Inmate Report', 'Generated by Admin');
    $pdf->setHeaderFont(['helvetica', '', 10]);
    $pdf->setFooterFont(['helvetica', '', 8]);
    $pdf->SetMargins(15, 27, 15);
    $pdf->SetAutoPageBreak(TRUE, 25);
    $pdf->AddPage();

    // Create PDF content
    $html = "
        <h1>Inmate Report</h1>
        <p>Total Number of Inmates: <strong>$totalInmates</strong></p>
    ";

    // Write content to PDF
    $pdf->writeHTML($html, true, false, true, false, '');

    // Define file path
    $filePath = 'reports/inmate_report.pdf';
    $pdf->Output($filePath, 'F'); // Save file to specified path

    // Return the file path for JavaScript to download
    echo json_encode(['status' => 'success', 'filePath' => $filePath]);
} catch (Exception $e) {
    echo json_encode(['status' => 'error', 'message' => $e->getMessage()]);
}

$conn->close();
